import * as fs from "fs";
import * as path from "path";
import { marked } from "marked";

export function saveChangelog(
  markdown: string,
  owner: string,
  repo: string
): string {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Changelog — ${owner}/${repo}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: #0f0f0f;
      color: #e8e8e8;
      min-height: 100vh;
      padding: 60px 24px;
    }

    .container {
      max-width: 760px;
      margin: 0 auto;
    }

    .header {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 48px;
      padding-bottom: 24px;
      border-bottom: 1px solid #222;
    }

    .repo-badge {
      font-size: 13px;
      font-weight: 600;
      color: #888;
      background: #1a1a1a;
      border: 1px solid #2a2a2a;
      padding: 4px 10px;
      border-radius: 20px;
      letter-spacing: 0.02em;
    }

    .generated-badge {
      font-size: 12px;
      color: #555;
      margin-left: auto;
    }

    .content h1 {
      font-size: 28px;
      font-weight: 700;
      color: #fff;
      margin-bottom: 32px;
      letter-spacing: -0.02em;
    }

    .content h2 {
      font-size: 13px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      color: #666;
      margin: 40px 0 16px;
      padding-bottom: 8px;
      border-bottom: 1px solid #1e1e1e;
    }

    .content h3 {
      font-size: 16px;
      font-weight: 600;
      color: #e0e0e0;
      margin: 24px 0 8px;
    }

    .content p {
      font-size: 15px;
      line-height: 1.7;
      color: #aaa;
      margin-bottom: 12px;
    }

    .content ul, .content ol {
      padding-left: 20px;
      margin-bottom: 12px;
    }

    .content li {
      font-size: 15px;
      line-height: 1.7;
      color: #aaa;
      margin-bottom: 4px;
    }

    .content code {
      font-family: 'SF Mono', 'Fira Code', monospace;
      font-size: 13px;
      background: #1a1a1a;
      border: 1px solid #2a2a2a;
      color: #7dd3fc;
      padding: 2px 6px;
      border-radius: 4px;
    }

    .content strong {
      color: #e0e0e0;
      font-weight: 600;
    }

    .content hr {
      border: none;
      border-top: 1px solid #1e1e1e;
      margin: 32px 0;
    }

    .footer {
      margin-top: 64px;
      padding-top: 24px;
      border-top: 1px solid #1a1a1a;
      font-size: 12px;
      color: #444;
      display: flex;
      justify-content: space-between;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <span class="repo-badge">${owner}/${repo}</span>
      <span class="generated-badge">Generated ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</span>
    </div>
    <div class="content">
      ${marked(markdown)}
    </div>
    <div class="footer">
      <span>Generated by ChangelogGenerator</span>
      <span>Powered by Claude + RAG</span>
    </div>
  </div>
</body>
</html>`;

  const outputDir = path.join(process.cwd(), "output");
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir);
  }

  const filename = `changelog-${owner}-${repo}-${Date.now()}.html`;
  const filepath = path.join(outputDir, filename);
  fs.writeFileSync(filepath, html);

  return filepath;
}